language: node_js
node_js:
- node
- '6'
- '4'
addons:
  code_climate:
    repo_token: a877074555c5f1836623cdaf5cf48c350ed17fcee5c8e3dc3ad53993c719e215
notifications:
  slack:
    rooms:
      secure: jBc9A9zXVCw6UgDLEUKRCzjp5br0qxEp1aNJDUA8/PnOa/H2lcv/tM4w1Zszrw/Z3EvF85/HOV2y949SZ/7x9OlYJS2pbGxzqlzwtGncXHFGwIyktr+EyGXsb8KrdYUkNE7P3xZCH8L6aNDMoXbuvhtE4CskyaUgs/veg4jJq+rD3O1ZY0bqLkDTFoN09s0ZaT8po4Ou9nQZLFejWezxZeWmsJyo8ODxhYdTGgTuhABvYqmAKy0zycVrkvQ9LP/x0B3Qz/4jJm2RUEbmBc7UaNN/EWpn6Mn3YrMkfPmJ/W6AdzF+S8F40Uf2ofmwFb0awjoe6dmPGVS8JgIWP+/Tn+QYP81EUrPY6Kp7I8pYnuZt6ZHRDq00qXYKGQxLX9PBypueermIF1m9NXLurbWJHektykOW+kt9RqFkcDgTgpIt1VcSGeKmoYxzUV80IlREK1u79vBB6huL8X6USJRW6Kf3yQjiajG9t76wMGieVxtb1NkUxb07hOGyLdQ5/rj+N8Xk6tmUJJsroAShBawlP1cKkHnCgrzdt25OvsxKOOQRLmLEMm9kwWubFSdJw2Q0z4rUpjBt8O2RuxfZ0lbV8dJvci92jyUsp7kFfBqTKk5EA6aN6xKLVuFK5FYwz0L2luaxFvjjaTi1a/o+fuW7EujY7QEb2uYHWG7WvDxpGT4=
  email: false
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
